/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/scene.gltf --types 
Author: GeniusPilot2016 (https://sketchfab.com/GeniusPilot2016)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-676e365f61f544e9a0236b7519e1bc90
Title: Laptop
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
  }
  materials: {
    ['case']: THREE.MeshStandardMaterial
    touchpad: THREE.MeshStandardMaterial
    ports: THREE.MeshStandardMaterial
    holes: THREE.MeshStandardMaterial
    ethernet_port: THREE.MeshStandardMaterial
    display: THREE.MeshStandardMaterial
    bezel: THREE.MeshStandardMaterial
    keyboard: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.501, 0.021, 0.454]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.115}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['case']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.touchpad} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.ports} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.holes} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.ethernet_port} />
      </group>
      <group position={[0.501, 0.028, 0.742]} rotation={[-1.309, 0, -Math.PI]} scale={[0.115, 0.055, 0.115]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['case']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.display} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.bezel} />
      </group>
      <mesh geometry={nodes.Object_14.geometry} material={materials.keyboard} position={[0.515, 0.037, 0.541]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.115} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')